# Generated by Django 4.1.7 on 2023-03-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adscategory_slug_markedads'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
            ],
            options={
                'verbose_name_plural': 'استان',
            },
        ),
        migrations.AddField(
            model_name='ads',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='ads',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ads', to='ads.provincecity'),
        ),
    ]
